name: Bottle

on:
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Build bottles
      run: brew install --build-bottle malleefoul/etc/

    - name: Extract bottles
      run: brew bottle julian/tap/fortune

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Bottles
        path: .